apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: components
  namespace: argocd
spec:
  project: cluster-components
  source:
    repoURL: https://github.com/hikaru-shindo/argocd-playground.git
    targetRevision: HEAD
    path: scenarios/raw-manifests
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
