gitea:
  persistence:
    enabled: true
    size: 1Gi
    annotations: {}

  redis-cluster:
    enabled: false

  postgresql:
    enabled: false

  postgresql-ha:
    enabled: false

  service:
    http:
      port: 80
      clusterIP: ~
    ssh:
      clusterIP: ~

  gitea:
    admin:
      username: gitops
      password: gitops
      email: gitops@gitea.cluster.local
    config:
      server:
        HTTP_PORT: 3000
      database:
        DB_TYPE: sqlite3
      session:
        PROVIDER: memory
      cache:
        ADAPTER: memory
      queue:
        TYPE: level
      indexer:
        ISSUE_INDEXER_TYPE: bleve
        REPO_INDEXER_ENABLED: true