apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: kube-state-metrics
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: kube-state-metrics
      version: "5.16.0"
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
        namespace: flux-system
      interval: 12h
  values:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
