apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
# finalizer disabled, because otherwise everything under this Application would be deleted as well, if this Application is deleted by accident
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: argocd
  source:
    path: argocd/
    repoURL: http://gitea-http.gitea.svc.cluster.local/argocd/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false # is set to false to prevent argo from deleting itself
      selfHeal: true