apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: cluster-addons
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.14.2
      helm:
        releaseName: cert-manager
        valueFiles: 
        - $values/apps/cert-manager/values.yaml
    - repoURL: http://gitea-http.gitea.svc.cluster.local/argocd/cluster-addons.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
