apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
spec:
  destination:
    namespace: ingress-controller
    server: https://kubernetes.default.svc
  project: cluster-addons
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.9.1
      helm:
        releaseName: ingress-nginx
        valueFiles: 
        - $values/apps/ingress-controller/values.yaml
    - repoURL: http://gitea-http.gitea.svc.cluster.local/argocd/cluster-addons.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
