apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misc
spec:
  project: cluster-addons
  destination:
    server: https://kubernetes.default.svc
  source:
    path: misc/
    repoURL: http://gitea-http.gitea.svc.cluster.local/argocd/cluster-addons.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true