apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misc
spec:
  project: cluster-addons
  destination:
    server: https://kubernetes.default.svc
  source:
    path: misc/
    repoURL: http://scm-manager.scm-manager.svc.cluster.local/scm/repo/gitops/cluster-addons
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true