apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: reloader
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: reloader
      version: "1.0.67"
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
      interval: 12h
  values:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
