apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: components
  namespace: argocd
spec:
  project: cluster-components
  sources:
  - repoURL: https://github.com/hikaru-shindo/argocd-playground.git
    targetRevision: HEAD
    path: scenarios/helm-multisource/components
    helm:
      releaseName: cluster-components
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
