apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: cluster-components
  sources:
  - chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.11.0
    helm:
      releaseName: cert-manager
      valueFiles: 
      - $values/{{ .Values.spec.source.values.path }}/cert-manager.yaml
  - repoURL: {{ .Values.spec.source.values.repoURL | quote }}
    targetRevision: HEAD
    ref: values
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true