apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  project: cluster-components
  sources:
  - chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 1.0.10
    helm:
      releaseName: reloader     
      valueFiles: 
      - $values/inventory/kind/reloader.yaml
  - repoURL: 'https://github.com/hikaru-shindo/argocd-playground.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true