apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: cert-manager
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: cert-manager
      version: "1.14.2"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true
    webhook:
      resources:
        requests:
          memory: 50Mi
          cpu: 10m
        limits:
          memory: 50Mi
    cainjector:
      resources:
        requests:
          memory: 100Mi
          cpu: 10m
        limits:
          memory: 100Mi
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 100Mi
