apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: cluster-components
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.11.0
    helm:
      releaseName: cert-manager
      parameters:
      {{- range $key, $value := index .Values "cert-manager" "values" }}
      - name: {{ $key | quote }}
        value: {{ $value | quote }}
      {{- end }}
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true