apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30m
  targetNamespace: ingress-nginx
  serviceAccountName: helm-controller
  chart:
    spec:
      chart: ingress-nginx
      version: "4.9.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 12h
  values:
    controller:
      replicaCount: 2
      minAvailable: 1
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
      enableCustomResources: true
      enableCertManager: true
      service:
        type: NodePort # No LoadBalancer in kind cluster :)
