installCRDs: true
webhook:
  resources:
    requests:
      memory: 50Mi
      cpu: 10m
    limits:
      memory: 50Mi

cainjector:
  resources:
    requests:
      memory: 100Mi
      cpu: 10m
    limits:
      memory: 100Mi

resources:
  requests:
    memory: 100Mi
    cpu: 50m
  limits:
    memory: 100Mi