apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-state-metrics
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.31.0
    helm:
      releaseName: kube-state-metrics
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: kube-state-metrics
