apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: cluster-components
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.5.2
    helm:
      releaseName: ingress-nginx
      parameters:
        - name: controller.replicaCount
          value: "2"
        - name: controller.minAvailable
          value: "1"
        - name: controller.resources.requests.cpu
          value: 100m
        - name: controller.resources.requests.memory
          value: 64Mi
        - name: controller.enableCustomResources
          value: "true"        
        - name: controller.enableCertManager
          value: "true"
        - name: controller.service.type
          value: NodePort # No LoadBalancer in kind cluster :)
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      