controller:
  replicaCount: 2
  minAvailable: 1
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
  enableCustomResources: true
  enableCertManager: true
  service:
    type: NodePort # No LoadBalancer in kind cluster :)
