apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: team-a-staging
spec:
  project: team-a
  destination:
    server: https://kubernetes.default.svc
    # a namespace must be specified here, because teams are not allowed to deploy cluster-wide.
    # You can specify a different namespace in the ressource YAMLs, if you are permitted to deploy in them
    namespace: team-a-staging
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
